### ISSUE TITLE
attiny85 support

### ISSUE THREAD

**Issue by theawsomeavr** [LenShustek/arduino-playtune#10]
hi, i know this has been posted before but i just wanted to share with you that i actually got it working with your original program from the menorah  the bad thing is since the attiny85 has very little space you run out of memory very often with 3 min long midis
https://github.com/theawsomeavr/Attiny85_Playtune_master

**Comment by LenShustek** [comment]
That's wonderful; thanks for telling me!
Yes, memory space on the ATtiny85 is a problem -- but it's fun to try to make the most of it. That reminds me of the "old days" when computers were made out of vacuum tubes.
Incidentally, there are newer and fancier versions of the MIDI compiler (miditones) at https://github.com/LenShustek/miditones, but if the old ones work for you, that's great.

**Comment by theawsomeavr** [comment]
it was because my computer is a 32 bit system, but yesterday i compile the new version and even created a gui interface in C#

**Comment by LenShustek** [comment]
Cool! I hope you eventually post the code for your GUI interface.

**Comment by theawsomeavr** [comment]
here you go https://github.com/theawsomeavr/midigui
it has been pre compiled for Windows x86

**Comment by theawsomeavr** [comment]
i have only tested on windows 7 an it works flawless
