### ISSUE TITLE
Trouble interaction of Plartune library with the Servo Library

### ISSUE THREAD

**Issue by Juarezdoposto** [LenShustek/arduino-playtune#12]
I was including the servo library on my song code that already works, and i have this message of compiling error

`libraries\Servo\avr\Servo.cpp.o (symbol from plugin): In function `ServoCount':
(.text+0x0): multiple definition of `__vector_11'
libraries\Playtune\Playtune.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
exit status 1
Erro compilando para a placa Arduino Uno
`
ps:Erro compilando para a placa Arduino Uno means error compiling for arduino uno board

I think that the servo library interprets some of the hexadecimals of the bytestream as defining constants for pins,maybe but i dont know.

**Comment by LenShustek** [comment]
The problem is that both Playtune and the Servo library are using the same hardware timers. They both try to define the interrupt routines for those timers, and so the compiler/linker complains. 
This is a fundamental problem that makes them incompatible; a timer can only be used by one program at a time.

**Comment by LenShustek** [comment]
If you can get the Servo library to not use Timer1, you can use a different version of Playtune that uses only that one timer, instead of using one timer for each simultaneous note. Then the two libraries will be able to coexist.
 https://github.com/LenShustek/Playtune_poll

**Comment by Juarezdoposto** [comment]
well,i solved this not using the servo library,instead i only use the timer when the song is over,to make the servo power direct from digital write using some calculus instead of the servo library and myservo.write.
