### ISSUE TITLE
Problem with tune() and playtune

### ISSUE THREAD

**Issue by natio94** [LenShustek/arduino-playtune#13]
I don't know if it was already said but it's normal that this library don't work with tune() ?

**Comment by LenShustek** [comment]
Yes, that's correct. They both use the same timers.

**Comment by natio94** [comment]
Thanks for the fast answer and sorry to reopen the issue. Do you know if there is a way to use both or it's really impossible ?
And if it's not possible, how can I know at which hexadecimal code correspond a note ? Otherwise, good job, it's very useful.

**Comment by MLXXXp** [comment]
@natio94 If you want to be able to intermix tones with a 1 or 2 part score, you could look into using or adapting [ArduboyPlaytune](https://github.com/Arduboy/ArduboyPlaytune).

**Comment by LenShustek** [comment]
The only way to use both is to have Playtune not use the timer that tune() uses, which depends on which arduino you are using. There are definitions starting at line 311 of Playtune.cpp that shows which timers Playtune uses. If you remove the one that tune() uses (and decrement AVAILABLE_TIMERS), then you can use both. But that reduces the number of notes that can play at the same time.

The codes that Playtune uses for notes are just the MIDI note numbers. You can see a table of them in hexadecimal here:
https://www.wavosaur.com/download/midi-note-hex.php

**Comment by LenShustek** [comment]
Another alternative, but which uses more CPU cycles, is https://github.com/LenShustek/Playtune_poll. It uses only one timer for playing multiple notes at the same time, so you can avoid the timer that tune() uses.

**Comment by natio94** [comment]
Thanks I'll will be looking for that.
