### ISSUE TITLE
avr/arduino.h in unsupported in new versions of arduino idle, use arduino.h instead

### ISSUE THREAD

**Issue by twkomp** [LenShustek/arduino-playtune#8]
avr/arduino.h is no longer supported with new versions with arduino. However when i change line 189 of playtune.cpp, and line 36 of playtune.h to `#include <Arduino.h>` , it fixes itself. I have attached the fixed files and the old ones. take a look and see if the library fix is needed.

[playtune_fixed.zip](https://github.com/LenShustek/arduino-playtune/files/754691/playtune_fixed.zip)
[playtune.zip](https://github.com/LenShustek/arduino-playtune/files/754692/playtune.zip)

**Comment by twkomp** [comment]
hold on I got arduino incorrect, the file name is Arduino.h

**Comment by LenShustek** [comment]
Thanks, but you started with a very old version, from 3+ years ago. The new one at https://github.com/LenShustek/arduino-playtune has that fix, and several others. Let me know if that works for you.

**Comment by twkomp** [comment]
thanks! I will see if that version works!
