### ISSUE TITLE
Disable after Playing Song

### ISSUE THREAD

**Issue by OptimusWide** [LenShustek/arduino-playtune#9]
I have a project where i want to play an intro song, and then use the arduino to turn on LED's like a simple clock.

Playtune is an awesome library, and exactly what i needed - but the problem i'm running into is I can't re-enable to the arduino delay() functions (after the song finishes playing at start up, after i'm done with the playtune library)

Is there any way to have all 3 channels available for playing a song, and then destory the object so arduino timer functions can be re-enabled?

tune_stopchans() doesn't seem to have any affect.

**Comment by OptimusWide** [comment]
I have a project where i want to play an intro song, and then use the arduino to turn on LED's like a simple clock.

The problem is I can't re-enable to the arduino delay() functions (after the song finishes playing at start up, after i'm done with the playtune library)

Is there any way to have all 3 channels available for playing a song, and then destory the object so arduino timer functions can be re-enabled?

tune_stopchans() doesn't seem to have any affect.

**Comment by LenShustek** [comment]
The problem is that the timer used by the arduino delay() function (timer 0) has been reset. 
Try this: Don't call tune_stopchans(). After the song ends, use tune_delay() to do the timing for your LEDs instead of delay().

**Comment by OptimusWide** [comment]
Thanks for the quick reply & awesome, that is working!

I've also got a button, which i'm using for inputs (long press vs. short press will do different functions) - any suggestion on what to use in place of millis() so i can still time the presses?

**Comment by LenShustek** [comment]
That's a little tougher. I can't offhand see a way to easily duplicate the millis() function after Playtune has taken over the timer.

One alternative scheme is to time the button presses with a polling loop that incorporates a call to tune_delay() for a fixed amount that is big compared to the overhead of checking the button, say 10 msec.  Count the number of times in the loop until the button stops being pressed.
